# -*- coding: utf-8 -*-
"""solution920.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19xFW3kTSnng3ZCeYp6BOMFxBTLI3g5aR
"""

for i in range(1,101):
  if i % 5 == 0:
    if i % 3 == 0:
      print("FizzBuzz",i)
    else:
      print("Buzz",i)
  elif i % 3 ==0:
    print("Fizz",i)
  else:
    print(i)